export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_PUNCHCARD = "ADD_PUNCHCARD";
export const GET_PUNCHCARDS = "GET_PUNCHCARDS";
export const GET_PUNCHCARD = "GET_PUNCHCARD";
export const PUNCHCARD_LOADING = "PUNCHCARD_LOADING";
